#!/usr/bin/env python3


from src import main


if __name__ == '__main__':
    while True:
        try: 
            main.Siem(main.args)

            break
        except Exception as e:
            print('Error : {}'.format(str(e)))

